package crypto

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"golang.org/x/crypto/curve25519"
)

// =============================================================================
// Libsodium test vector infrastructure
//
// Vectors generated by PyNaCl (libsodium) — see testdata/generate_vectors.py.
// Every deterministic primitive is verified byte-for-byte against libsodium.
// Every encryption vector is generated by Python and decrypted by Go.
// =============================================================================

type testVectors struct {
	SeedKeypairs      []seedKeypairVector  `json:"seed_keypairs"`
	Blake2bDigests    []blake2bVector      `json:"blake2b_digests"`
	SessionKeys       sessionKeyVector     `json:"session_keys"`
	EncryptRaw        []encryptRawVector   `json:"encrypt_raw"`
	AsymmetricEncrypt []asymmetricVector   `json:"asymmetric_encrypt"`
	XORReconstruct    []xorVector          `json:"xor_reconstruct"`
}

type seedKeypairVector struct {
	Seed       string `json:"seed"`
	PublicKey  string `json:"public_key"`
	PrivateKey string `json:"private_key"`
}

type blake2bVector struct {
	Input  string `json:"input"`
	Salt   string `json:"salt"`
	Digest string `json:"digest"`
}

type sessionKeyVector struct {
	SeedA       string `json:"seed_a"`
	SeedB       string `json:"seed_b"`
	PublicKeyA  string `json:"public_key_a"`
	PrivateKeyA string `json:"private_key_a"`
	PublicKeyB  string `json:"public_key_b"`
	PrivateKeyB string `json:"private_key_b"`
	ClientRx    string `json:"client_rx"`
	ClientTx    string `json:"client_tx"`
	ServerRx    string `json:"server_rx"`
	ServerTx    string `json:"server_tx"`
}

type encryptRawVector struct {
	Plaintext           string `json:"plaintext"`
	Key                 string `json:"key"`
	CiphertextWithNonce string `json:"ciphertext_with_nonce"`
}

type asymmetricVector struct {
	Plaintext           string `json:"plaintext"`
	RecipientSeed       string `json:"recipient_seed"`
	RecipientPublicKey  string `json:"recipient_public_key"`
	RecipientPrivateKey string `json:"recipient_private_key"`
	Ciphertext          string `json:"ciphertext"`
}

type xorVector struct {
	Shares   []string `json:"shares"`
	Expected string   `json:"expected"`
}

func loadVectors(t *testing.T) testVectors {
	t.Helper()
	_, filename, _, _ := runtime.Caller(0)
	path := filepath.Join(filepath.Dir(filename), "testdata", "test_vectors.json")

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("Failed to read test vectors: %v", err)
	}

	var v testVectors
	if err := json.Unmarshal(data, &v); err != nil {
		t.Fatalf("Failed to parse test vectors: %v", err)
	}
	return v
}

// =============================================================================
// XORBytes
// =============================================================================

func TestXORBytes(t *testing.T) {
	tests := []struct {
		name     string
		a        []byte
		b        []byte
		expected []byte
		wantErr  bool
	}{
		{
			name:     "basic XOR",
			a:        []byte{0x00, 0xFF, 0xAA, 0x55},
			b:        []byte{0xFF, 0xFF, 0x55, 0xAA},
			expected: []byte{0xFF, 0x00, 0xFF, 0xFF},
		},
		{
			name:     "XOR with zeros is identity",
			a:        []byte{0x12, 0x34, 0x56, 0x78},
			b:        []byte{0x00, 0x00, 0x00, 0x00},
			expected: []byte{0x12, 0x34, 0x56, 0x78},
		},
		{
			name:     "XOR with self is zero",
			a:        []byte{0xDE, 0xAD, 0xBE, 0xEF},
			b:        []byte{0xDE, 0xAD, 0xBE, 0xEF},
			expected: []byte{0x00, 0x00, 0x00, 0x00},
		},
		{
			name:     "empty slices",
			a:        []byte{},
			b:        []byte{},
			expected: []byte{},
		},
		{
			name:    "length mismatch",
			a:       []byte{0x00, 0xFF},
			b:       []byte{0xFF},
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result, err := XORBytes(tt.a, tt.b)
			if tt.wantErr {
				if err == nil {
					t.Error("expected error, got nil")
				}
				return
			}
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if !bytes.Equal(result, tt.expected) {
				t.Errorf("got %x, want %x", result, tt.expected)
			}
		})
	}
}

func TestXORBytesReversibility(t *testing.T) {
	a := make([]byte, 32)
	b := make([]byte, 32)
	rand.Read(a)
	rand.Read(b)

	xored, err := XORBytes(a, b)
	if err != nil {
		t.Fatalf("XORBytes() error: %v", err)
	}

	recovered, err := XORBytes(xored, b)
	if err != nil {
		t.Fatalf("XORBytes() error: %v", err)
	}

	if !bytes.Equal(recovered, a) {
		t.Errorf("(a ^ b) ^ b != a: got %x, want %x", recovered, a)
	}
}

// =============================================================================
// ReconstructSecret
// =============================================================================

func TestReconstructSecret(t *testing.T) {
	t.Run("error handling", func(t *testing.T) {
		cases := []struct {
			name   string
			share1 string
			share2 string
		}{
			{"invalid hex share1", "xyz", "cafe"},
			{"invalid hex share2", "cafe", "xyz"},
			{"length mismatch", "deadbeef", "cafe"},
		}
		for _, tc := range cases {
			t.Run(tc.name, func(t *testing.T) {
				_, err := ReconstructSecret(tc.share1, tc.share2)
				if err == nil {
					t.Error("expected error, got nil")
				}
			})
		}
	})

	// Verify against libsodium vectors
	t.Run("libsodium vectors", func(t *testing.T) {
		v := loadVectors(t)
		for _, tc := range v.XORReconstruct {
			t.Run(tc.Shares[0][:16]+"...", func(t *testing.T) {
				result, err := ReconstructSecret(tc.Shares[0], tc.Shares[1])
				if err != nil {
					t.Fatalf("error: %v", err)
				}
				if result != tc.Expected {
					t.Errorf("mismatch\n  go:        %s\n  libsodium: %s", result, tc.Expected)
				}
			})
		}
	})
}

// =============================================================================
// Blake2bDigest
// =============================================================================

func TestBlake2bDigest(t *testing.T) {
	// Go-only known answer tests (unkeyed BLAKE2b-256)
	t.Run("unkeyed known answers", func(t *testing.T) {
		tests := []struct {
			input    string
			expected string
		}{
			{"", "0e5751c026e543b2e8ab2eb06099daa1d1e5df47778f7787faab45cdf12fe3a8"},
			{"hello world", "256c83b297114d201b30179f3f0ef0cace9783622da5974326b436178aeef610"},
		}
		for _, tt := range tests {
			name := tt.input
			if name == "" {
				name = "(empty)"
			}
			t.Run(name, func(t *testing.T) {
				result, err := Blake2bDigest(tt.input, "")
				if err != nil {
					t.Fatalf("error: %v", err)
				}
				if result != tt.expected {
					t.Errorf("got %s, want %s", result, tt.expected)
				}
			})
		}
	})

	// Verify against libsodium vectors (keyed + unkeyed, unicode, long input)
	t.Run("libsodium vectors", func(t *testing.T) {
		v := loadVectors(t)
		for _, tc := range v.Blake2bDigests {
			name := tc.Input
			if len(name) > 30 {
				name = name[:30] + "..."
			}
			if name == "" {
				name = "(empty)"
			}
			t.Run(name, func(t *testing.T) {
				digest, err := Blake2bDigest(tc.Input, tc.Salt)
				if err != nil {
					t.Fatalf("error: %v", err)
				}
				if digest != tc.Digest {
					t.Errorf("mismatch (salt=%q)\n  go:        %s\n  libsodium: %s", tc.Salt, digest, tc.Digest)
				}
			})
		}
	})

	t.Run("salt changes output", func(t *testing.T) {
		input := "test data"
		h1, _ := Blake2bDigest(input, "")
		h2, _ := Blake2bDigest(input, "salt1")
		h3, _ := Blake2bDigest(input, "salt2")

		if h1 == h2 {
			t.Error("keyed hash should differ from unkeyed")
		}
		if h2 == h3 {
			t.Error("different salts should produce different hashes")
		}
	})

	t.Run("deterministic", func(t *testing.T) {
		h1, _ := Blake2bDigest("deterministic test", "my-salt")
		h2, _ := Blake2bDigest("deterministic test", "my-salt")
		if h1 != h2 {
			t.Errorf("not deterministic: %s != %s", h1, h2)
		}
	})
}

// =============================================================================
// Key Pair Generation
// =============================================================================

func TestRandomKeyPair(t *testing.T) {
	kp1, err := RandomKeyPair()
	if err != nil {
		t.Fatalf("error: %v", err)
	}

	var zeroKey [32]byte
	if kp1.PublicKey == zeroKey {
		t.Error("public key should not be all zeros")
	}
	if kp1.SecretKey == zeroKey {
		t.Error("secret key should not be all zeros")
	}

	// Two random keypairs must differ
	kp2, err := RandomKeyPair()
	if err != nil {
		t.Fatalf("error: %v", err)
	}
	if kp1.PublicKey == kp2.PublicKey || kp1.SecretKey == kp2.SecretKey {
		t.Error("random keypairs should be unique")
	}
}

func TestRandomKeyPairDerivation(t *testing.T) {
	kp, err := RandomKeyPair()
	if err != nil {
		t.Fatalf("error: %v", err)
	}

	derivedSlice, err := curve25519.X25519(kp.SecretKey[:], curve25519.Basepoint)
	if err != nil {
		t.Fatalf("X25519 error: %v", err)
	}
	var derived [32]byte
	copy(derived[:], derivedSlice)
	if derived != kp.PublicKey {
		t.Error("public key not correctly derived from secret key")
	}
}

func TestGenerateEnvKeyPair(t *testing.T) {
	// Verify against libsodium's crypto_kx_seed_keypair
	t.Run("libsodium vectors", func(t *testing.T) {
		v := loadVectors(t)
		for _, tc := range v.SeedKeypairs {
			t.Run(tc.Seed[:16]+"...", func(t *testing.T) {
				pub, priv, err := GenerateEnvKeyPair(tc.Seed)
				if err != nil {
					t.Fatalf("error: %v", err)
				}
				if pub != tc.PublicKey {
					t.Errorf("public key mismatch\n  go:        %s\n  libsodium: %s", pub, tc.PublicKey)
				}
				if priv != tc.PrivateKey {
					t.Errorf("private key mismatch\n  go:        %s\n  libsodium: %s", priv, tc.PrivateKey)
				}
			})
		}
	})

	t.Run("deterministic", func(t *testing.T) {
		seed := "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
		pub1, priv1, _ := GenerateEnvKeyPair(seed)
		pub2, priv2, _ := GenerateEnvKeyPair(seed)
		if pub1 != pub2 || priv1 != priv2 {
			t.Error("same seed should produce same keys")
		}
	})

	t.Run("different seeds differ", func(t *testing.T) {
		seed1 := "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
		seed2 := "fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210"
		pub1, _, _ := GenerateEnvKeyPair(seed1)
		pub2, _, _ := GenerateEnvKeyPair(seed2)
		if pub1 == pub2 {
			t.Error("different seeds should produce different keys")
		}
	})

	t.Run("invalid input", func(t *testing.T) {
		if _, _, err := GenerateEnvKeyPair("xyz"); err == nil {
			t.Error("expected error for invalid hex")
		}
		if _, _, err := GenerateEnvKeyPair("0123456789abcdef"); err == nil {
			t.Error("expected error for wrong length")
		}
	})
}

// =============================================================================
// Session Key Derivation
// =============================================================================

func TestSessionKeys(t *testing.T) {
	// Verify exact values against libsodium's crypto_kx_client/server_session_keys
	t.Run("libsodium vectors", func(t *testing.T) {
		v := loadVectors(t)
		sk := v.SessionKeys

		// Verify seed → keypair derivation as a prerequisite
		pubA, privA, _ := GenerateEnvKeyPair(sk.SeedA)
		if pubA != sk.PublicKeyA || privA != sk.PrivateKeyA {
			t.Fatal("seed_a keypair mismatch — cannot test session keys")
		}
		pubB, privB, _ := GenerateEnvKeyPair(sk.SeedB)
		if pubB != sk.PublicKeyB || privB != sk.PrivateKeyB {
			t.Fatal("seed_b keypair mismatch — cannot test session keys")
		}

		// Build keypairs
		kpA := mustKeyPairFromHex(t, sk.PublicKeyA, sk.PrivateKeyA)
		kpB := mustKeyPairFromHex(t, sk.PublicKeyB, sk.PrivateKeyB)

		// Client session keys: A is client, B is server
		clientKeys, err := ClientSessionKeys(kpA, kpB.PublicKey[:])
		if err != nil {
			t.Fatalf("ClientSessionKeys error: %v", err)
		}
		if got := hex.EncodeToString(clientKeys.Rx[:]); got != sk.ClientRx {
			t.Errorf("client rx mismatch\n  go:        %s\n  libsodium: %s", got, sk.ClientRx)
		}
		if got := hex.EncodeToString(clientKeys.Tx[:]); got != sk.ClientTx {
			t.Errorf("client tx mismatch\n  go:        %s\n  libsodium: %s", got, sk.ClientTx)
		}

		// Server session keys: B is server, A is client
		serverKeys, err := ServerSessionKeys(kpB, kpA.PublicKey[:])
		if err != nil {
			t.Fatalf("ServerSessionKeys error: %v", err)
		}
		if got := hex.EncodeToString(serverKeys.Rx[:]); got != sk.ServerRx {
			t.Errorf("server rx mismatch\n  go:        %s\n  libsodium: %s", got, sk.ServerRx)
		}
		if got := hex.EncodeToString(serverKeys.Tx[:]); got != sk.ServerTx {
			t.Errorf("server tx mismatch\n  go:        %s\n  libsodium: %s", got, sk.ServerTx)
		}

		// The critical duplex property
		if sk.ClientTx != sk.ServerRx {
			t.Errorf("client.Tx != server.Rx — key exchange broken")
		}
		if sk.ClientRx != sk.ServerTx {
			t.Errorf("client.Rx != server.Tx — key exchange broken")
		}
	})

	t.Run("symmetry with random keys", func(t *testing.T) {
		clientKP, _ := RandomKeyPair()
		serverKP, _ := RandomKeyPair()

		clientKeys, err := ClientSessionKeys(clientKP, serverKP.PublicKey[:])
		if err != nil {
			t.Fatalf("ClientSessionKeys error: %v", err)
		}
		serverKeys, err := ServerSessionKeys(serverKP, clientKP.PublicKey[:])
		if err != nil {
			t.Fatalf("ServerSessionKeys error: %v", err)
		}

		if clientKeys.Tx != serverKeys.Rx {
			t.Error("client.Tx != server.Rx")
		}
		if clientKeys.Rx != serverKeys.Tx {
			t.Error("client.Rx != server.Tx")
		}
	})

	t.Run("deterministic", func(t *testing.T) {
		clientKP, _ := RandomKeyPair()
		serverKP, _ := RandomKeyPair()

		k1, _ := ClientSessionKeys(clientKP, serverKP.PublicKey[:])
		k2, _ := ClientSessionKeys(clientKP, serverKP.PublicKey[:])
		if k1.Tx != k2.Tx || k1.Rx != k2.Rx {
			t.Error("ClientSessionKeys not deterministic")
		}
	})

	t.Run("invalid public key length", func(t *testing.T) {
		kp, _ := RandomKeyPair()
		if _, err := ClientSessionKeys(kp, []byte{0x00, 0x01, 0x02}); err == nil {
			t.Error("expected error for short public key")
		}
		if _, err := ServerSessionKeys(kp, []byte{0x00, 0x01, 0x02}); err == nil {
			t.Error("expected error for short public key")
		}
	})
}

// =============================================================================
// Symmetric Encryption (XChaCha20-Poly1305)
// =============================================================================

func TestEncryptDecryptRaw(t *testing.T) {
	t.Run("round trip", func(t *testing.T) {
		key := randomKey()
		plaintexts := []string{
			"",
			"hello",
			"hello world",
			"The quick brown fox jumps over the lazy dog",
			strings.Repeat("a", 1000),
			strings.Repeat("🔐", 100),
		}

		for _, pt := range plaintexts {
			name := pt
			if len(name) > 20 {
				name = name[:20] + "..."
			}
			if name == "" {
				name = "(empty)"
			}
			t.Run(name, func(t *testing.T) {
				ct, err := EncryptRaw(pt, key)
				if err != nil {
					t.Fatalf("EncryptRaw error: %v", err)
				}
				got, err := DecryptRaw(ct, key)
				if err != nil {
					t.Fatalf("DecryptRaw error: %v", err)
				}
				if string(got) != pt {
					t.Errorf("got %q, want %q", string(got), pt)
				}
			})
		}
	})

	// Decrypt ciphertext generated by Python/libsodium
	t.Run("decrypt libsodium ciphertext", func(t *testing.T) {
		v := loadVectors(t)
		for _, tc := range v.EncryptRaw {
			name := tc.Plaintext
			if len(name) > 30 {
				name = name[:30] + "..."
			}
			if name == "" {
				name = "(empty)"
			}
			t.Run(name, func(t *testing.T) {
				key := mustKeyFromHex(t, tc.Key)
				ct, _ := hex.DecodeString(tc.CiphertextWithNonce)

				got, err := DecryptRaw(ct, key)
				if err != nil {
					t.Fatalf("failed to decrypt libsodium ciphertext: %v", err)
				}
				if string(got) != tc.Plaintext {
					t.Errorf("got %q, want %q", string(got), tc.Plaintext)
				}
			})
		}
	})

	t.Run("wrong key fails", func(t *testing.T) {
		ct, _ := EncryptRaw("secret", randomKey())
		if _, err := DecryptRaw(ct, randomKey()); err == nil {
			t.Error("expected error when decrypting with wrong key")
		}
	})

	t.Run("tampered ciphertext fails", func(t *testing.T) {
		key := randomKey()
		ct, _ := EncryptRaw("secret message", key)
		ct[5] ^= 0xFF // flip a byte in the ciphertext body
		if _, err := DecryptRaw(ct, key); err == nil {
			t.Error("expected error for tampered ciphertext")
		}
	})

	t.Run("unique ciphertext per encryption", func(t *testing.T) {
		key := randomKey()
		ct1, _ := EncryptRaw("same", key)
		ct2, _ := EncryptRaw("same", key)
		if bytes.Equal(ct1, ct2) {
			t.Error("same plaintext should produce different ciphertext (random nonce)")
		}
	})

	t.Run("ciphertext length", func(t *testing.T) {
		key := randomKey()
		ct, _ := EncryptRaw("test", key)
		// plaintext(4) + poly1305 tag(16) + nonce(24) = 44
		if len(ct) != 44 {
			t.Errorf("ciphertext length = %d, want 44", len(ct))
		}
	})
}

func TestEncryptDecryptB64(t *testing.T) {
	key := randomKey()
	pt := "secret message for base64 encoding"

	ct, err := EncryptB64(pt, key)
	if err != nil {
		t.Fatalf("EncryptB64 error: %v", err)
	}

	got, err := DecryptB64(ct, key)
	if err != nil {
		t.Fatalf("DecryptB64 error: %v", err)
	}
	if got != pt {
		t.Errorf("got %q, want %q", got, pt)
	}
}

// =============================================================================
// Asymmetric Encryption (ph:v1:ephemeral_pk:b64_ct)
// =============================================================================

func TestEncryptDecryptAsymmetric(t *testing.T) {
	t.Run("round trip", func(t *testing.T) {
		recipientKP, _ := RandomKeyPair()
		pubHex := hex.EncodeToString(recipientKP.PublicKey[:])
		privHex := hex.EncodeToString(recipientKP.SecretKey[:])

		plaintexts := []string{
			"short",
			"medium length secret message",
			strings.Repeat("long", 250),
			"unicode: 日本語 🔐 émoji",
		}

		for _, pt := range plaintexts {
			name := pt
			if len(name) > 20 {
				name = name[:20] + "..."
			}
			t.Run(name, func(t *testing.T) {
				ct, err := EncryptAsymmetric(pt, pubHex)
				if err != nil {
					t.Fatalf("EncryptAsymmetric error: %v", err)
				}

				// Verify format
				parts := strings.Split(ct, ":")
				if len(parts) != 4 || parts[0] != "ph" || parts[1] != "v1" || len(parts[2]) != 64 {
					t.Fatalf("invalid ciphertext format: %s", ct)
				}

				got, err := DecryptAsymmetric(ct, privHex, pubHex)
				if err != nil {
					t.Fatalf("DecryptAsymmetric error: %v", err)
				}
				if got != pt {
					t.Errorf("got %q, want %q", got, pt)
				}
			})
		}
	})

	// Decrypt ciphertext generated by Python/libsodium
	t.Run("decrypt libsodium ciphertext", func(t *testing.T) {
		v := loadVectors(t)
		for _, tc := range v.AsymmetricEncrypt {
			name := tc.Plaintext
			if len(name) > 30 {
				name = name[:30] + "..."
			}
			t.Run(name, func(t *testing.T) {
				got, err := DecryptAsymmetric(tc.Ciphertext, tc.RecipientPrivateKey, tc.RecipientPublicKey)
				if err != nil {
					t.Fatalf("failed to decrypt libsodium ciphertext: %v", err)
				}
				if got != tc.Plaintext {
					t.Errorf("got %q, want %q", got, tc.Plaintext)
				}
			})
		}
	})

	t.Run("wrong key fails", func(t *testing.T) {
		recipientKP, _ := RandomKeyPair()
		wrongKP, _ := RandomKeyPair()
		ct, _ := EncryptAsymmetric("secret", hex.EncodeToString(recipientKP.PublicKey[:]))

		_, err := DecryptAsymmetric(ct,
			hex.EncodeToString(wrongKP.SecretKey[:]),
			hex.EncodeToString(wrongKP.PublicKey[:]))
		if err == nil {
			t.Error("expected error when decrypting with wrong key")
		}
	})

	t.Run("unique ciphertext per encryption", func(t *testing.T) {
		recipientKP, _ := RandomKeyPair()
		pubHex := hex.EncodeToString(recipientKP.PublicKey[:])

		ct1, _ := EncryptAsymmetric("same", pubHex)
		ct2, _ := EncryptAsymmetric("same", pubHex)
		if ct1 == ct2 {
			t.Error("same plaintext should produce different ciphertext (ephemeral keypair + nonce)")
		}
	})
}

// =============================================================================
// Security
// =============================================================================

func TestNonceUniqueness(t *testing.T) {
	key := randomKey()
	seen := make(map[string]bool, 100)

	for i := 0; i < 100; i++ {
		ct, _ := EncryptRaw("test", key)
		nonce := hex.EncodeToString(ct[len(ct)-24:])
		if seen[nonce] {
			t.Fatalf("nonce collision on iteration %d", i)
		}
		seen[nonce] = true
	}
}

// =============================================================================
// Benchmarks
// =============================================================================

func BenchmarkEncryptRaw(b *testing.B) {
	key := randomKeyB()
	pt := strings.Repeat("a", 1024)
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		EncryptRaw(pt, key)
	}
}

func BenchmarkDecryptRaw(b *testing.B) {
	key := randomKeyB()
	ct, _ := EncryptRaw(strings.Repeat("a", 1024), key)
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		DecryptRaw(ct, key)
	}
}

func BenchmarkBlake2bDigest(b *testing.B) {
	input := strings.Repeat("a", 1024)
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		Blake2bDigest(input, "benchmark-salt")
	}
}

func BenchmarkSessionKeys(b *testing.B) {
	clientKP, _ := RandomKeyPair()
	serverKP, _ := RandomKeyPair()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		ClientSessionKeys(clientKP, serverKP.PublicKey[:])
	}
}

func BenchmarkEncryptAsymmetric(b *testing.B) {
	recipientKP, _ := RandomKeyPair()
	pubHex := hex.EncodeToString(recipientKP.PublicKey[:])
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		EncryptAsymmetric("benchmark secret message", pubHex)
	}
}

// =============================================================================
// Helpers
// =============================================================================

func randomKey() [32]byte {
	var k [32]byte
	rand.Read(k[:])
	return k
}

func randomKeyB() [32]byte {
	var k [32]byte
	rand.Read(k[:])
	return k
}

func mustKeyFromHex(t *testing.T, h string) [32]byte {
	t.Helper()
	b, err := hex.DecodeString(h)
	if err != nil {
		t.Fatalf("invalid hex key: %v", err)
	}
	var k [32]byte
	copy(k[:], b)
	return k
}

func mustKeyPairFromHex(t *testing.T, pubHex, privHex string) KeyPair {
	t.Helper()
	pub, _ := hex.DecodeString(pubHex)
	priv, _ := hex.DecodeString(privHex)
	var kp KeyPair
	copy(kp.PublicKey[:], pub)
	copy(kp.SecretKey[:], priv)
	return kp
}
