package phase

// =============================================================================
// Backwards Compatibility Test Suite
//
// Verifies that the v2 pure-Go SDK produces identical crypto outputs and
// follows the same workflows as the v1 libsodium-based SDK. Since the 1.x
// SDK requires CGO + system libsodium, this suite embeds the 1.x SDK's
// expected behavior via hardcoded test vectors generated by libsodium (PyNaCl).
//
// Coverage:
//   1. Crypto primitives: identical output for all deterministic operations
//   2. Ciphertext format: ph:v1:{epk}:{b64ct} unchanged
//   3. Full key reconstruction workflow: token -> keyshare unwrap -> XOR -> decrypt
//   4. Environment key derivation: seed -> BLAKE2b -> Curve25519 keypair
//   5. Phase.Decrypt workflow: keyshare unwrap -> reconstruct -> decrypt
//   6. Secret encryption/decryption round-trip: 1.x ciphertext decrypts with 2.x code
//   7. PhaseGetContext: app/env resolution matching 1.x behavior
//   8. DecryptSecret helper: 1.x API response format handling
//   9. Cross-SDK encrypt/decrypt interoperability
// =============================================================================

import (
	"encoding/base64"
	"encoding/hex"
	"strings"
	"testing"

	"github.com/phasehq/golang-sdk/v2/phase/crypto"
	"github.com/phasehq/golang-sdk/v2/phase/misc"
)

// =============================================================================
// 1. Crypto Primitive Compatibility
//
// These verify that the 2.x pure-Go crypto produces byte-identical output
// to the 1.x libsodium-based SDK for all deterministic operations.
// =============================================================================

func TestCompat_GenerateEnvKeyPair_MatchesLibsodium(t *testing.T) {
	// Vectors generated by libsodium's crypto_kx_seed_keypair (via PyNaCl 1.6.2)
	// The 1.x SDK called sodium.SeedKXKP(seed) which wraps this exact function.
	vectors := []struct {
		seed       string
		publicKey  string
		privateKey string
	}{
		{
			seed:       "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
			publicKey:  "24eaf70f070a925d6d5176f20495d4d90867624d9a10379e2a9aef0955c9bf4e",
			privateKey: "b85c84f9828524519d32b97cd3dda961fdba2dbf407ae4601e2129229aa463c2",
		},
		{
			seed:       "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
			publicKey:  "7fb9d9f66d4dc570f707c96b528d775516d7ba4e5feb83d2c55719a91857fb2c",
			privateKey: "046c0d987075db8217087bae19e9f753305890fc6772908c57f07878211cc8cb",
		},
		{
			seed:       "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
			publicKey:  "d3b715edf936a0f7168b2b4972212aba706f5a7ab9d968e903cf7058a77dd752",
			privateKey: "ca011d08f3f0afd580957644f31648ca2e0175e01144b760a37c88c7e0ac9af1",
		},
	}

	for _, v := range vectors {
		t.Run(v.seed[:16]+"...", func(t *testing.T) {
			pub, priv, err := crypto.GenerateEnvKeyPair(v.seed)
			if err != nil {
				t.Fatalf("GenerateEnvKeyPair error: %v", err)
			}
			if pub != v.publicKey {
				t.Errorf("public key mismatch with libsodium:\n  got:      %s\n  expected: %s", pub, v.publicKey)
			}
			if priv != v.privateKey {
				t.Errorf("private key mismatch with libsodium:\n  got:      %s\n  expected: %s", priv, v.privateKey)
			}
		})
	}
}

func TestCompat_Blake2bDigest_MatchesLibsodium(t *testing.T) {
	// Vectors generated by libsodium's crypto_generichash (BLAKE2b-256)
	// The 1.x SDK called sodium.NewGenericHashKeyed / sodium.NewGenericHash
	vectors := []struct {
		input  string
		salt   string
		digest string
	}{
		// Keyed hash
		{"hello", "world", "38010cfe3a8e684cb17e6d049525e71d4e9dc3be173fc05bf5c5ca1c7e7c25e7"},
		// Keyed hash with empty input
		{"", "some-salt", "27e29d6aff0af8d5df144e7a82e59d3e1bdd2963b6ba5a1a51efbf088c39a8bb"},
		// Unkeyed hash
		{"phase secrets manager", "", "6c9295d6d31af938dcb6a3730839aa782731565531ac6fad1a25f643f9199ab4"},
		// Unicode input
		{"unicode: 日本語 emoji 🔐", "salt-value", "714a0d63dbc6af0f74e02105786259f5edb287766f701d78a077ab1a9e5d59f2"},
	}

	for _, v := range vectors {
		name := v.input
		if name == "" {
			name = "(empty)"
		}
		if len(name) > 30 {
			name = name[:30] + "..."
		}
		t.Run(name, func(t *testing.T) {
			digest, err := crypto.Blake2bDigest(v.input, v.salt)
			if err != nil {
				t.Fatalf("Blake2bDigest error: %v", err)
			}
			if digest != v.digest {
				t.Errorf("digest mismatch with libsodium (salt=%q):\n  got:      %s\n  expected: %s", v.salt, digest, v.digest)
			}
		})
	}
}

func TestCompat_SessionKeys_MatchesLibsodium(t *testing.T) {
	// Vectors generated by libsodium's crypto_kx_client/server_session_keys
	// The 1.x SDK called kp.ClientSessionKeys(recipientPubKey) and
	// kp.ServerSessionKeys(clientPubKey) which wrap these exact functions.
	seedA := "1111111111111111111111111111111111111111111111111111111111111111"
	seedB := "2222222222222222222222222222222222222222222222222222222222222222"

	expectedClientRx := "b0053e142960e91d365043abe725043e227e745ff53fa1f4815056b45a0bc4ea"
	expectedClientTx := "0f8fd492c10c2dd3dca73ccb41f633d20109e94a4a4a1bbbc3e39387633faa9f"
	expectedServerRx := "0f8fd492c10c2dd3dca73ccb41f633d20109e94a4a4a1bbbc3e39387633faa9f"
	expectedServerTx := "b0053e142960e91d365043abe725043e227e745ff53fa1f4815056b45a0bc4ea"

	pubA, privA, _ := crypto.GenerateEnvKeyPair(seedA)
	pubB, privB, _ := crypto.GenerateEnvKeyPair(seedB)

	kpA := mustBuildKeyPair(t, pubA, privA)
	kpB := mustBuildKeyPair(t, pubB, privB)

	clientKeys, err := crypto.ClientSessionKeys(kpA, kpB.PublicKey[:])
	if err != nil {
		t.Fatalf("ClientSessionKeys error: %v", err)
	}

	if got := hex.EncodeToString(clientKeys.Rx[:]); got != expectedClientRx {
		t.Errorf("client Rx mismatch:\n  got:      %s\n  expected: %s", got, expectedClientRx)
	}
	if got := hex.EncodeToString(clientKeys.Tx[:]); got != expectedClientTx {
		t.Errorf("client Tx mismatch:\n  got:      %s\n  expected: %s", got, expectedClientTx)
	}

	serverKeys, err := crypto.ServerSessionKeys(kpB, kpA.PublicKey[:])
	if err != nil {
		t.Fatalf("ServerSessionKeys error: %v", err)
	}

	if got := hex.EncodeToString(serverKeys.Rx[:]); got != expectedServerRx {
		t.Errorf("server Rx mismatch:\n  got:      %s\n  expected: %s", got, expectedServerRx)
	}
	if got := hex.EncodeToString(serverKeys.Tx[:]); got != expectedServerTx {
		t.Errorf("server Tx mismatch:\n  got:      %s\n  expected: %s", got, expectedServerTx)
	}

	// The critical duplex property: client.Tx == server.Rx and vice versa
	if hex.EncodeToString(clientKeys.Tx[:]) != hex.EncodeToString(serverKeys.Rx[:]) {
		t.Error("BROKEN: client.Tx != server.Rx — key exchange incompatible")
	}
	if hex.EncodeToString(clientKeys.Rx[:]) != hex.EncodeToString(serverKeys.Tx[:]) {
		t.Error("BROKEN: client.Rx != server.Tx — key exchange incompatible")
	}
}

func TestCompat_DecryptRaw_LibsodiumCiphertext(t *testing.T) {
	// Ciphertext generated by libsodium's crypto_aead_xchacha20poly1305_ietf_encrypt
	// The 1.x SDK used sodium.Bytes.AEADXCPEncrypt with the same format:
	// ciphertext || nonce (24 bytes appended at end)
	vectors := []struct {
		plaintext           string
		key                 string
		ciphertextWithNonce string
	}{
		{
			"hello world",
			"abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
			"38e81e26784df4d55585c2a465378c45aa4385e9df29fd11d5a72046491ede02b3f0cbe1fc67da5d118526e302ccc131d25c73",
		},
		{
			"phase secrets are safe",
			"abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
			"2d1188962da7f6733fb21eb2b25f073649f9fd8fa4f522df4c4fc6cf42e982b432b2be49607949a81d6b3552fee67a379eabac0d9e9bebbabbea4e599b5f",
		},
		{
			"unicode: 日本語 🔐 émoji",
			"abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
			"cb2ec7a62831d71957229aca6872dff1449cd21e82016047d34d511eb0cfe990bcb8282602ee799a0013ede33ece7e727bcb810e38b98d2ffee9f0c9e2ba3d13bc3e8151c052",
		},
		{
			"",
			"abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
			"9cfe59047467fc0063718a8a9bed7eb169f3d50a06e098e00cd6c820fd2c57504c09e4901f4db547",
		},
	}

	for _, v := range vectors {
		name := v.plaintext
		if name == "" {
			name = "(empty)"
		}
		t.Run(name, func(t *testing.T) {
			keyBytes, _ := hex.DecodeString(v.key)
			var key [32]byte
			copy(key[:], keyBytes)

			ct, _ := hex.DecodeString(v.ciphertextWithNonce)

			got, err := crypto.DecryptRaw(ct, key)
			if err != nil {
				t.Fatalf("DecryptRaw failed on libsodium ciphertext: %v", err)
			}
			if string(got) != v.plaintext {
				t.Errorf("decrypted value mismatch:\n  got:      %q\n  expected: %q", string(got), v.plaintext)
			}
		})
	}
}

func TestCompat_DecryptAsymmetric_LibsodiumCiphertext(t *testing.T) {
	// Ciphertext generated by PyNaCl using the same encrypt flow as 1.x SDK:
	// 1. Generate ephemeral X25519 keypair
	// 2. crypto_kx_client_session_keys(ephemeral, recipient_pk) -> tx key
	// 3. crypto_aead_xchacha20poly1305_ietf_encrypt(plaintext, tx_key, random_nonce)
	// 4. Format: ph:v1:{ephemeral_pk_hex}:{base64(ciphertext||nonce)}
	vectors := []struct {
		plaintext  string
		publicKey  string
		privateKey string
		ciphertext string
	}{
		{
			"secret-api-key-12345",
			"0c4dd67e4067217a07ba10caefc6202c22e47f47ace33d47ea0f6d1d38230a37",
			"ba7bd8fbe711f27e0d726b0ec94c8f3da6963f787abd6c77a2c9d0464b09a545",
			"ph:v1:9d3ac13a04e1a68273ac8ce341f215b988f93b444a72098817ba87f934795d02:2JYKMsRIhehCa1PPVHkDxyR8ST7xfPvc5MgBIpHfHFPW0hjD2n5f3qIJAzCgOIbBHjkcDSeehtWpp+d/",
		},
		{
			"DATABASE_URL=postgres://user:pass@host:5432/db",
			"0c4dd67e4067217a07ba10caefc6202c22e47f47ace33d47ea0f6d1d38230a37",
			"ba7bd8fbe711f27e0d726b0ec94c8f3da6963f787abd6c77a2c9d0464b09a545",
			"ph:v1:9bbed7eb730a3ceb0f37222db4a87e75f2924d31b0036a3e96e24a29f7b36750:X//CgLuQ0og9mtRH5Uik7mh5Zo+dwLSCqsBeVA8Ha/Y/Q7hLBduuwISjTzaOER9ihNAhIIwr3nmF6x4c8A1JOOjgDbLDBVl6Zt8gptY1RZE5u4MC8gI=",
		},
		{
			"multi\nline\nsecret\nvalue",
			"0c4dd67e4067217a07ba10caefc6202c22e47f47ace33d47ea0f6d1d38230a37",
			"ba7bd8fbe711f27e0d726b0ec94c8f3da6963f787abd6c77a2c9d0464b09a545",
			"ph:v1:3ded99d5658e52dd9eb073de959eb3a575b227a007675d206d1188b9a4b9d654:VJ02aL5AgfRWh+XpcZp7k/JkNnlQi/CJntVo0gILRZIHZ1YvZlb9xVQcRLn0dtTxH3+3N1VyzYq4wN5BXRhV",
		},
		{
			"unicode: 日本語テスト 🔑🔒",
			"0c4dd67e4067217a07ba10caefc6202c22e47f47ace33d47ea0f6d1d38230a37",
			"ba7bd8fbe711f27e0d726b0ec94c8f3da6963f787abd6c77a2c9d0464b09a545",
			"ph:v1:bda3ff916e3f497f91265b638a4a77ebd728111904ae7d0515e5a81201cd0f40:gHXgUXCKnGZY0w1eKeisYWFo+g19nkPAfz7Dt2nfy8ls14kckHw8L0iVgEl7C2w1Z97Pwyr87peAJlnaHOiK984dRIWL6KXMRlRqxw==",
		},
	}

	for _, v := range vectors {
		name := v.plaintext
		if len(name) > 30 {
			name = name[:30] + "..."
		}
		t.Run(name, func(t *testing.T) {
			got, err := crypto.DecryptAsymmetric(v.ciphertext, v.privateKey, v.publicKey)
			if err != nil {
				t.Fatalf("DecryptAsymmetric failed on libsodium ciphertext: %v", err)
			}
			if got != v.plaintext {
				t.Errorf("decrypted value mismatch:\n  got:      %q\n  expected: %q", got, v.plaintext)
			}
		})
	}
}

func TestCompat_XORReconstruct_MatchesLibsodium(t *testing.T) {
	vectors := []struct {
		share1   string
		share2   string
		expected string
	}{
		{
			"6eed8a70ac9e75ab1894b06d4a5e21d1072649529753f3244316c6d9e4c9c951",
			"a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8091a2b3c4d5e6f708192a3b4c5d6",
			"cf5f49a44968d213d144519fe9eae407e0de4048bc6fbe7a2c66474b477d0c87",
		},
		{
			"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
			"0000000000000000000000000000000000000000000000000000000000000000",
			"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
		},
		{
			"abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
			"abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
			"0000000000000000000000000000000000000000000000000000000000000000",
		},
	}

	for _, v := range vectors {
		t.Run(v.share1[:16]+"...", func(t *testing.T) {
			result, err := crypto.ReconstructSecret(v.share1, v.share2)
			if err != nil {
				t.Fatalf("ReconstructSecret error: %v", err)
			}
			if result != v.expected {
				t.Errorf("XOR mismatch:\n  got:      %s\n  expected: %s", result, v.expected)
			}
		})
	}
}

// =============================================================================
// 2. Ciphertext Format Compatibility
//
// Verify the ciphertext wire format is identical between old and 2.x SDK.
// =============================================================================

func TestCompat_CiphertextFormat_PhV1(t *testing.T) {
	// The 1.x SDK produced: ph:v1:{64-char-hex-ephemeral-pk}:{base64-ciphertext}
	// Verify the 2.x SDK produces the same format.
	recipientKP, _ := crypto.RandomKeyPair()
	pubHex := hex.EncodeToString(recipientKP.PublicKey[:])

	ct, err := crypto.EncryptAsymmetric("test secret", pubHex)
	if err != nil {
		t.Fatalf("EncryptAsymmetric error: %v", err)
	}

	parts := strings.Split(ct, ":")
	if len(parts) != 4 {
		t.Fatalf("expected 4 colon-separated parts, got %d: %s", len(parts), ct)
	}
	if parts[0] != "ph" {
		t.Errorf("expected prefix 'ph', got %q", parts[0])
	}
	if parts[1] != "v1" {
		t.Errorf("expected version 'v1', got %q", parts[1])
	}
	if len(parts[2]) != 64 {
		t.Errorf("expected 64-char hex ephemeral public key, got %d chars", len(parts[2]))
	}
	if _, err := hex.DecodeString(parts[2]); err != nil {
		t.Errorf("ephemeral public key is not valid hex: %v", err)
	}
	if _, err := base64.StdEncoding.DecodeString(parts[3]); err != nil {
		t.Errorf("ciphertext body is not valid base64: %v", err)
	}
}

func TestCompat_CiphertextFormat_NoncePosition(t *testing.T) {
	// Both old and 2.x SDK append the 24-byte nonce to the end of the
	// XChaCha20-Poly1305 ciphertext. Verify this layout.
	keyBytes, _ := hex.DecodeString("abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789")
	var key [32]byte
	copy(key[:], keyBytes)

	ct, err := crypto.EncryptRaw("test", key)
	if err != nil {
		t.Fatalf("EncryptRaw error: %v", err)
	}

	// Expected length: plaintext(4) + poly1305_tag(16) + nonce(24) = 44
	if len(ct) != 44 {
		t.Fatalf("ciphertext length = %d, expected 44", len(ct))
	}

	// Nonce is the last 24 bytes — extract and verify we can decrypt with it
	nonce := ct[len(ct)-24:]
	if len(nonce) != 24 {
		t.Fatalf("extracted nonce length = %d, expected 24", len(nonce))
	}

	// Verify round-trip (proves nonce position is correct)
	got, err := crypto.DecryptRaw(ct, key)
	if err != nil {
		t.Fatalf("DecryptRaw failed: %v", err)
	}
	if string(got) != "test" {
		t.Errorf("round-trip decryption mismatch: got %q, want %q", string(got), "test")
	}
}

// =============================================================================
// 3. Full Key Reconstruction Workflow
//
// Simulates the complete workflow that both old and 2.x SDKs perform:
// Token -> fetch wrapped keyshare -> unwrap -> XOR reconstruct -> decrypt seed
// =============================================================================

func TestCompat_FullKeyReconstructionWorkflow(t *testing.T) {
	// Simulate what the server would store and what the SDK reconstructs.
	// This tests the exact same sequence both old and 2.x SDKs perform:
	//
	// 1. Start with an app private key (what we want to reconstruct)
	// 2. Split into keyshare0 and keyshare1 via XOR
	// 3. Encrypt keyshare1 with unwrapKey -> wrappedKeyShare
	// 4. Reconstruct: decrypt wrappedKeyShare -> keyshare1, then XOR(keyshare0, keyshare1) -> appPrivKey
	// 5. Use appPrivKey to decrypt asymmetric ciphertext

	// Step 1: Generate a deterministic "app private key" from a known seed
	seed := "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
	appPubHex, appPrivHex, err := crypto.GenerateEnvKeyPair(seed)
	if err != nil {
		t.Fatalf("GenerateEnvKeyPair error: %v", err)
	}

	// Step 2: Split into shares
	keyshare0Hex := "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
	appPrivBytes, _ := hex.DecodeString(appPrivHex)
	ks0Bytes, _ := hex.DecodeString(keyshare0Hex)
	ks1Bytes, _ := crypto.XORBytes(appPrivBytes, ks0Bytes)
	keyshare1Hex := hex.EncodeToString(ks1Bytes)

	// Step 3: Encrypt keyshare1 with a known unwrap key
	unwrapKeyHex := "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
	unwrapKeyBytes, _ := hex.DecodeString(unwrapKeyHex)
	var unwrapKey [32]byte
	copy(unwrapKey[:], unwrapKeyBytes)

	wrappedKeyShare, err := crypto.EncryptRaw(keyshare1Hex, unwrapKey)
	if err != nil {
		t.Fatalf("EncryptRaw (wrap keyshare1) error: %v", err)
	}

	// Step 4: Reconstruct (this is what both old and 2.x SDK do)
	decryptedKS1, err := crypto.DecryptRaw(wrappedKeyShare, unwrapKey)
	if err != nil {
		t.Fatalf("DecryptRaw (unwrap keyshare1) error: %v", err)
	}
	if string(decryptedKS1) != keyshare1Hex {
		t.Fatalf("unwrapped keyshare1 mismatch:\n  got:      %s\n  expected: %s", string(decryptedKS1), keyshare1Hex)
	}

	reconstructedPrivKey, err := crypto.ReconstructSecret(keyshare0Hex, string(decryptedKS1))
	if err != nil {
		t.Fatalf("ReconstructSecret error: %v", err)
	}
	if reconstructedPrivKey != appPrivHex {
		t.Fatalf("reconstructed private key mismatch:\n  got:      %s\n  expected: %s", reconstructedPrivKey, appPrivHex)
	}

	// Step 5: Encrypt a secret with the public key and decrypt with the reconstructed private key
	plaintext := "MY_SECRET_VALUE=hunter2"
	ct, err := crypto.EncryptAsymmetric(plaintext, appPubHex)
	if err != nil {
		t.Fatalf("EncryptAsymmetric error: %v", err)
	}

	got, err := crypto.DecryptAsymmetric(ct, reconstructedPrivKey, appPubHex)
	if err != nil {
		t.Fatalf("DecryptAsymmetric error: %v", err)
	}
	if got != plaintext {
		t.Errorf("end-to-end decryption mismatch:\n  got:      %q\n  expected: %q", got, plaintext)
	}
}

func TestCompat_Encrypt2xDecrypt1xWorkflow(t *testing.T) {
	// Verify that ciphertext produced by the 2.x SDK can be consumed by
	// something following the 1.x SDK's decryption logic exactly.
	//
	// 1.x SDK's DecryptAsymmetric did:
	// 1. Parse ph:v1:{epk_hex}:{b64_ct}
	// 2. Build KeyPair from recipient's keys
	// 3. Call ServerSessionKeys(recipientKP, ephemeralPK)
	// 4. DecryptB64(b64_ct, sessionKeys.Rx)
	//
	// We replicate this step by step.

	recipientKP, _ := crypto.RandomKeyPair()
	pubHex := hex.EncodeToString(recipientKP.PublicKey[:])
	privHex := hex.EncodeToString(recipientKP.SecretKey[:])

	// Encrypt with 2.x SDK
	plaintext := "secret encrypted by v2 SDK"
	ct, err := crypto.EncryptAsymmetric(plaintext, pubHex)
	if err != nil {
		t.Fatalf("EncryptAsymmetric error: %v", err)
	}

	// Manually replicate the 1.x SDK's DecryptAsymmetric logic:
	segments := strings.Split(ct, ":")
	if len(segments) != 4 || segments[0] != "ph" || segments[1] != "v1" {
		t.Fatalf("unexpected ciphertext format: %s", ct)
	}

	ephPKBytes, _ := hex.DecodeString(segments[2])
	privKeyBytes, _ := hex.DecodeString(privHex)
	pubKeyBytes, _ := hex.DecodeString(pubHex)

	var kp crypto.KeyPair
	copy(kp.PublicKey[:], pubKeyBytes)
	copy(kp.SecretKey[:], privKeyBytes)

	// 1.x SDK: serverKeys, _ := ServerSessionKeys(kp, ephemeralPublicKeyBytes)
	serverKeys, err := crypto.ServerSessionKeys(kp, ephPKBytes)
	if err != nil {
		t.Fatalf("ServerSessionKeys error: %v", err)
	}

	// 1.x SDK: plaintext, _ := DecryptB64(segments[3], serverKeys.Rx)
	got, err := crypto.DecryptB64(segments[3], serverKeys.Rx)
	if err != nil {
		t.Fatalf("DecryptB64 error: %v", err)
	}
	if got != plaintext {
		t.Errorf("1.x-style decryption of 2.x ciphertext failed:\n  got:      %q\n  expected: %q", got, plaintext)
	}
}

// =============================================================================
// 4. Environment Keypair Derivation Workflow
//
// Test the full chain: seed -> BLAKE2b -> Curve25519 -> keypair
// This is used to derive per-environment encryption keys.
// =============================================================================

func TestCompat_EnvKeyDerivationChain(t *testing.T) {
	// The seed is decrypted from WrappedSeed via the app private key.
	// Both old and 2.x SDKs then call GenerateEnvKeyPair(seed) to get the
	// environment's encryption keypair. Verify the full chain:

	// Simulate: decrypt a wrapped seed, then derive env keys
	seed := "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
	salt := "cafecafecafecafecafecafecafecafe"

	// Generate env keypair
	pubHex, privHex, err := crypto.GenerateEnvKeyPair(seed)
	if err != nil {
		t.Fatalf("GenerateEnvKeyPair error: %v", err)
	}

	// Encrypt a key name and value (simulating secret creation)
	keyName := "DATABASE_URL"
	keyValue := "postgres://user:pass@host:5432/db"

	encKey, err := crypto.EncryptAsymmetric(keyName, pubHex)
	if err != nil {
		t.Fatalf("EncryptAsymmetric (key) error: %v", err)
	}

	encValue, err := crypto.EncryptAsymmetric(keyValue, pubHex)
	if err != nil {
		t.Fatalf("EncryptAsymmetric (value) error: %v", err)
	}

	// Generate key digest (for server-side lookup)
	keyDigest, err := crypto.Blake2bDigest(keyName, salt)
	if err != nil {
		t.Fatalf("Blake2bDigest error: %v", err)
	}

	// Verify key digest is deterministic (same as what 1.x SDK would produce)
	keyDigest2, _ := crypto.Blake2bDigest(keyName, salt)
	if keyDigest != keyDigest2 {
		t.Error("Blake2bDigest is not deterministic")
	}

	// Decrypt the secret (simulating secret retrieval)
	decKey, err := crypto.DecryptAsymmetric(encKey, privHex, pubHex)
	if err != nil {
		t.Fatalf("DecryptAsymmetric (key) error: %v", err)
	}
	decValue, err := crypto.DecryptAsymmetric(encValue, privHex, pubHex)
	if err != nil {
		t.Fatalf("DecryptAsymmetric (value) error: %v", err)
	}

	if decKey != keyName {
		t.Errorf("key name mismatch: got %q, want %q", decKey, keyName)
	}
	if decValue != keyValue {
		t.Errorf("key value mismatch: got %q, want %q", decValue, keyValue)
	}

	// Verify key digest matches expected (same for both 1.x and 2.x)
	if len(keyDigest) != 64 {
		t.Errorf("key digest should be 64 hex chars (32 bytes), got %d", len(keyDigest))
	}
}

// =============================================================================
// 5. Phase.Decrypt Workflow Compatibility
//
// The 1.x SDK used crypto.DecryptWrappedKeyShare (which fetched + decrypted).
// The 2.x SDK uses Phase.Decrypt (which takes pre-fetched data).
// Verify the decryption logic is identical when given the same inputs.
// =============================================================================

func TestCompat_DecryptMethod_MatchesCryptoWorkflow(t *testing.T) {
	// In the Phase system, PssUserPublicKey is the PUBLIC key of the app's
	// keypair, and the app private key is reconstructed from keyshare0 XOR keyshare1.
	// DecryptAsymmetric(ct, appPrivKey, PssUserPublicKey) requires these to form
	// a valid keypair: PssUserPublicKey = ScalarBaseMult(appPrivKey).
	//
	// The 1.x SDK's DecryptWrappedKeyShare did the same flow:
	// 1. Fetch wrapped keyshare from server
	// 2. Decrypt it with unwrapKey -> keyshare1
	// 3. Reconstruct appPrivKey = XOR(keyshare0, keyshare1)
	// 4. DecryptAsymmetric(ciphertext, appPrivKey, PssUserPublicKey)

	// Step 1: Generate one keypair for the app. Its public key = PssUserPublicKey.
	appSeed := "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
	appPubHex, appPrivHex, err := crypto.GenerateEnvKeyPair(appSeed)
	if err != nil {
		t.Fatalf("GenerateEnvKeyPair error: %v", err)
	}

	// Step 2: Split the app private key into keyshare0 and keyshare1
	keyshare0Hex := "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
	appPrivBytes, _ := hex.DecodeString(appPrivHex)
	ks0Bytes, _ := hex.DecodeString(keyshare0Hex)
	ks1Bytes, _ := crypto.XORBytes(appPrivBytes, ks0Bytes)
	keyshare1Hex := hex.EncodeToString(ks1Bytes)

	// Step 3: Wrap keyshare1 with an unwrap key (simulating server storage)
	unwrapKeyHex := "cafecafecafecafecafecafecafecafecafecafecafecafecafecafecafecafe"
	unwrapKeyBytes, _ := hex.DecodeString(unwrapKeyHex)
	var unwrapKey [32]byte
	copy(unwrapKey[:], unwrapKeyBytes)

	wrappedKeyShareBytes, err := crypto.EncryptRaw(keyshare1Hex, unwrapKey)
	if err != nil {
		t.Fatalf("EncryptRaw error: %v", err)
	}
	wrappedKeyShareHex := hex.EncodeToString(wrappedKeyShareBytes)

	// Step 4: Encrypt a "seed" with the app's public key (simulating WrappedSeed)
	envSeed := "fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210"
	wrappedSeed, err := crypto.EncryptAsymmetric(envSeed, appPubHex)
	if err != nil {
		t.Fatalf("EncryptAsymmetric error: %v", err)
	}

	// Step 5: Build Phase instance with the app's public key as pssUserPublicKey
	p := &Phase{
		keyshare0:          keyshare0Hex,
		keyshare1UnwrapKey: unwrapKeyHex,
		pssUserPublicKey:   appPubHex,
	}

	// Step 6: Call Phase.Decrypt (the 2.x SDK method) with wrapped key share directly
	decryptedSeed, err := p.Decrypt(wrappedSeed, wrappedKeyShareHex)
	if err != nil {
		t.Fatalf("Phase.Decrypt error: %v", err)
	}

	if decryptedSeed != envSeed {
		t.Errorf("Phase.Decrypt result mismatch:\n  got:      %q\n  expected: %q", decryptedSeed, envSeed)
	}

	// Step 8: Verify the 1.x SDK workflow produces the same result
	// (manually replicate DecryptWrappedKeyShare without the network call)
	decryptedKS1, err := crypto.DecryptRaw(wrappedKeyShareBytes, unwrapKey)
	if err != nil {
		t.Fatalf("manual unwrap keyshare1 error: %v", err)
	}
	manualAppPrivKey, err := crypto.ReconstructSecret(keyshare0Hex, string(decryptedKS1))
	if err != nil {
		t.Fatalf("manual ReconstructSecret error: %v", err)
	}
	if manualAppPrivKey != appPrivHex {
		t.Fatalf("reconstructed private key != original")
	}
	manualDecrypted, err := crypto.DecryptAsymmetric(wrappedSeed, manualAppPrivKey, appPubHex)
	if err != nil {
		t.Fatalf("manual DecryptAsymmetric error: %v", err)
	}
	if manualDecrypted != decryptedSeed {
		t.Errorf("Phase.Decrypt and manual workflow produced different results:\n  Phase.Decrypt: %q\n  manual:        %q", decryptedSeed, manualDecrypted)
	}
}

// =============================================================================
// 6. PhaseGetContext Compatibility
//
// The 1.x SDK's PhaseGetContext(userData, opts) returned (appID, envID, pubKey, err).
// The 2.x SDK returns (appName, appID, envName, envID, identityKey, err).
// Verify the resolution logic matches.
// =============================================================================

func TestCompat_PhaseGetContext_1xBehavior(t *testing.T) {
	userData := &misc.AppKeyResponse{
		Apps: []misc.App{
			{
				ID:   "app-1",
				Name: "Backend API",
				EnvironmentKeys: []misc.EnvironmentKey{
					{
						Environment: misc.Environment{ID: "env-dev", Name: "Development"},
						IdentityKey: "pub-dev-key",
					},
					{
						Environment: misc.Environment{ID: "env-prod", Name: "Production"},
						IdentityKey: "pub-prod-key",
					},
				},
			},
			{
				ID:   "app-2",
				Name: "Frontend",
				EnvironmentKeys: []misc.EnvironmentKey{
					{
						Environment: misc.Environment{ID: "env-stage", Name: "Staging"},
						IdentityKey: "pub-stage-key",
					},
				},
			},
		},
	}

	tests := []struct {
		name        string
		appName     string
		appID       string
		envName     string
		wantAppName string
		wantAppID   string
		wantEnvName string
		wantEnvID   string
		wantPubKey  string
		wantErr     bool
	}{
		{
			name:        "exact match by app ID",
			appID:       "app-1",
			envName:     "Production",
			wantAppName: "Backend API", wantAppID: "app-1",
			wantEnvName: "Production", wantEnvID: "env-prod", wantPubKey: "pub-prod-key",
		},
		{
			name:        "partial match by app name",
			appName:     "backend",
			envName:     "Development",
			wantAppName: "Backend API", wantAppID: "app-1",
			wantEnvName: "Development", wantEnvID: "env-dev", wantPubKey: "pub-dev-key",
		},
		{
			name:        "case insensitive env match",
			appID:       "app-2",
			envName:     "staging",
			wantAppName: "Frontend", wantAppID: "app-2",
			wantEnvName: "Staging", wantEnvID: "env-stage", wantPubKey: "pub-stage-key",
		},
		{
			name:        "default env when empty",
			appName:     "backend api",
			envName:     "",
			wantAppName: "Backend API", wantAppID: "app-1",
			wantEnvName: "Development", wantEnvID: "env-dev", wantPubKey: "pub-dev-key",
		},
		{
			name:    "missing app",
			appName: "does-not-exist",
			envName: "Development",
			wantErr: true,
		},
		{
			name:    "missing env",
			appID:   "app-2",
			envName: "Production",
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			appName, appID, envName, envID, pubKey, err := misc.PhaseGetContext(userData, tt.appName, tt.envName, tt.appID)

			if tt.wantErr {
				if err == nil {
					t.Fatal("expected error, got nil")
				}
				return
			}
			if err != nil {
				t.Fatalf("PhaseGetContext error: %v", err)
			}

			if appName != tt.wantAppName {
				t.Errorf("appName = %q, want %q", appName, tt.wantAppName)
			}
			if appID != tt.wantAppID {
				t.Errorf("appID = %q, want %q", appID, tt.wantAppID)
			}
			if envName != tt.wantEnvName {
				t.Errorf("envName = %q, want %q", envName, tt.wantEnvName)
			}
			if envID != tt.wantEnvID {
				t.Errorf("envID = %q, want %q", envID, tt.wantEnvID)
			}
			if pubKey != tt.wantPubKey {
				t.Errorf("pubKey = %q, want %q", pubKey, tt.wantPubKey)
			}
		})
	}
}

// =============================================================================
// 7. DecryptSecret Helper Compatibility
//
// The 1.x SDK's crypto.DecryptSecret(secret, privHex, pubHex) decrypted
// key, value, and comment from a map[string]interface{} (API response).
// Verify the 2.x code handles the same input format.
// =============================================================================

func TestCompat_DecryptSecret_1xAPIResponseFormat(t *testing.T) {
	// Generate environment keypair
	seed := "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
	pubHex, privHex, _ := crypto.GenerateEnvKeyPair(seed)

	// Encrypt key, value, comment (as the server would store them)
	encKey, _ := crypto.EncryptAsymmetric("MY_SECRET", pubHex)
	encVal, _ := crypto.EncryptAsymmetric("super-secret-value", pubHex)
	encComment, _ := crypto.EncryptAsymmetric("This is a secret comment", pubHex)

	// Build a mock API response (same format as what the server returns)
	apiSecret := map[string]interface{}{
		"id":      "uuid-123",
		"key":     encKey,
		"value":   encVal,
		"comment": encComment,
		"path":    "/",
		"tags":    []interface{}{"production", "database"},
		"override": map[string]interface{}{
			"value":     "",
			"is_active": false,
		},
	}

	// Decrypt using the same function both SDKs use
	decKey, decVal, decComment, err := crypto.DecryptSecret(apiSecret, privHex, pubHex)
	if err != nil {
		t.Fatalf("DecryptSecret error: %v", err)
	}

	if decKey != "MY_SECRET" {
		t.Errorf("key = %q, want %q", decKey, "MY_SECRET")
	}
	if decVal != "super-secret-value" {
		t.Errorf("value = %q, want %q", decVal, "super-secret-value")
	}
	if decComment != "This is a secret comment" {
		t.Errorf("comment = %q, want %q", decComment, "This is a secret comment")
	}
}

func TestCompat_DecryptSecret_EmptyComment(t *testing.T) {
	// Both old and 2.x SDKs skip decryption when comment is empty.
	seed := "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
	pubHex, privHex, _ := crypto.GenerateEnvKeyPair(seed)

	encKey, _ := crypto.EncryptAsymmetric("KEY", pubHex)
	encVal, _ := crypto.EncryptAsymmetric("value", pubHex)

	apiSecret := map[string]interface{}{
		"key":     encKey,
		"value":   encVal,
		"comment": "", // empty comment
	}

	_, _, decComment, err := crypto.DecryptSecret(apiSecret, privHex, pubHex)
	if err != nil {
		t.Fatalf("DecryptSecret error: %v", err)
	}
	if decComment != "" {
		t.Errorf("expected empty comment, got %q", decComment)
	}
}

// =============================================================================
// 8. Cross-SDK Encrypt/Decrypt Interoperability
//
// Verify that secrets encrypted by the 2.x SDK can be consumed by any
// implementation following the libsodium protocol, and vice versa.
// =============================================================================

func TestCompat_CrossSDK_EncryptDecryptRoundTrip(t *testing.T) {
	// Simulate: Python SDK (libsodium) encrypts -> Go SDK (v2) decrypts
	// and:      Go SDK (v2) encrypts -> Python SDK (libsodium) decrypts
	//
	// Since we can't run Python here, we verify the invariants:
	// 1. Ciphertext format is ph:v1:{hex}:{base64}
	// 2. The base64 payload, when decoded, is (ciphertext || nonce)
	// 3. The ephemeral key is a valid X25519 public key (32 bytes)
	// 4. Round-trip works with the same key material

	// Use the test vector recipient keys (from PyNaCl)
	recipientPubHex := "0c4dd67e4067217a07ba10caefc6202c22e47f47ace33d47ea0f6d1d38230a37"
	recipientPrivHex := "ba7bd8fbe711f27e0d726b0ec94c8f3da6963f787abd6c77a2c9d0464b09a545"

	plaintexts := []string{
		"simple",
		"",
		"multi\nline\nvalue",
		"unicode: 日本語 🔐 émoji",
		strings.Repeat("long-", 200),
		"key=value&special=chars!@#$%^&*()",
	}

	for _, pt := range plaintexts {
		name := pt
		if len(name) > 30 {
			name = name[:30] + "..."
		}
		if name == "" {
			name = "(empty)"
		}

		t.Run(name, func(t *testing.T) {
			// Encrypt with 2.x Go SDK
			ct, err := crypto.EncryptAsymmetric(pt, recipientPubHex)
			if err != nil {
				t.Fatalf("EncryptAsymmetric error: %v", err)
			}

			// Verify format
			parts := strings.Split(ct, ":")
			if len(parts) != 4 {
				t.Fatalf("expected 4 parts, got %d", len(parts))
			}
			if parts[0] != "ph" || parts[1] != "v1" {
				t.Fatalf("unexpected prefix: %s:%s", parts[0], parts[1])
			}

			epkBytes, err := hex.DecodeString(parts[2])
			if err != nil || len(epkBytes) != 32 {
				t.Fatalf("ephemeral public key invalid: len=%d err=%v", len(epkBytes), err)
			}

			b64Decoded, err := base64.StdEncoding.DecodeString(parts[3])
			if err != nil {
				t.Fatalf("base64 decode error: %v", err)
			}
			// Must be at least nonce(24) + tag(16) = 40 bytes
			if len(b64Decoded) < 40 {
				t.Fatalf("decoded payload too short: %d bytes", len(b64Decoded))
			}

			// Decrypt
			got, err := crypto.DecryptAsymmetric(ct, recipientPrivHex, recipientPubHex)
			if err != nil {
				t.Fatalf("DecryptAsymmetric error: %v", err)
			}
			if got != pt {
				t.Errorf("round-trip mismatch:\n  got:      %q\n  expected: %q", got, pt)
			}
		})
	}
}

// =============================================================================
// Helpers
// =============================================================================

func mustBuildKeyPair(t *testing.T, pubHex, privHex string) crypto.KeyPair {
	t.Helper()
	pubBytes, err := hex.DecodeString(pubHex)
	if err != nil {
		t.Fatalf("invalid public key hex: %v", err)
	}
	privBytes, err := hex.DecodeString(privHex)
	if err != nil {
		t.Fatalf("invalid private key hex: %v", err)
	}
	var kp crypto.KeyPair
	copy(kp.PublicKey[:], pubBytes)
	copy(kp.SecretKey[:], privBytes)
	return kp
}
